### ISSUE TITLE
如何设置关闭日志输出

### ISSUE THREAD

**Issue by mds1455975151** [ucloud/ucloud-sdk-python2#6]
2019-07-24 16:29:34,345 - ucloud - INFO - [request] DescribeUHostInstance {'Action': 'DescribeUHostInstance', 'ProjectId': u'xxx', 'Region': u'tw-tp'}

**Comment by yufeiminds** [comment]
Hi，@mds1455975151

你好，Python SDK 使用标准库 logging 来输出日志，并已统一置于 `ucloud` 及其子 logger 下，可以使用以下代码来更改日志设置

```python
logger = logging.getLogger('ucloud')
logger.disabled = True
```

详情可参考

- https://docs.python.org/zh-cn/3/howto/logging.html
- [SDK 源码](https://ucloud.github.io/ucloud-sdk-python2/_modules/ucloud/core/client/_client.html#Client)

在下星期的迭代中我们会补足相关文档，感谢您的反馈~

Best Regards
SDK Team

**Comment by mds1455975151** [comment]
已经解决，辛苦
